[package]
name = "sirius_extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.20"
json = "0.12.4"
futures = "0.3.28"

[dependencies.async-std]
version = "1.12"
features = ["tokio1"]